sudo: required

language: python
python:
 - "3.6"
 
services:
  - docker
env:
  - USERNAME = earthdatastore
  - PASSWORD = earthdatastore123
  - BRANCH = edsbyoa
  
script:  
 - docker build -t $USERNAME/$BRANCH .
 - docker run earthdatastore/eds-byoa

after_script:
 - docker images

before_deploy:
 - docker login -u "earthdatastore" -p "earthdatastore123"
 
deploy:
 provider: script
 script: docker push earthdatastore/eds-byoa:latest
 on:
  branch: master

 
