sudo: required

language: python
python:
 - "3.6"
 
services:
  - docker

script:  
 - docker build -t earthdatastore/eds-byoa .
 - docker push earthdatastore/eds-byoa:myimage
 - docker run myimage

after_script:
- docker images

